Repository janelia-cellmap/dacapo, pull requests merged in 2024-02, with the labels that each got.

#71 Suppress Scipy warning
  dacapo/gp/elastic_augment_fuse.py
Labels: bug

#1 Attention unet
  dacapo/experiments/architectures/cnnectome_unet.py
  dacapo/experiments/architectures/cnnectome_unet_config.py
Labels: feature

#70 Dev/balancing
  dacapo/experiments/tasks/affinities_task.py
  dacapo/experiments/tasks/affinities_task_config.py
  dacapo/experiments/tasks/distance_task.py
  dacapo/experiments/tasks/distance_task_config.py
  dacapo/experiments/tasks/predictors/affinities_predictor.py
  dacapo/experiments/tasks/predictors/distance_predictor.py
  dacapo/experiments/trainers/gunpowder_trainer.py
  dacapo/experiments/trainers/gunpowder_trainer_config.py
Labels: bug, enhancement

#88 Update daisy dependency to use a specific branch for speed improvements
  pyproject.toml
Labels: enhancement
